services:

  scraper:
    build: .
    container_name: playwright_scraper
    shm_size: "2g"  # Prevents shared memory issues
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=0  # Ensures browsers are installed inside the container
    command: tail -f /dev/null
    volumes:
      - ./src/:/src/
